### ISSUE TITLE
`set-output` is being deprecated

### ISSUE THREAD

**Issue by Rody-Oldenhuis** [phish108/autotag-action#190]
As per [this 2022 blogpost](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the `set-output` command is being deprecated. This results in job warnings: 

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. 

This requires a bit of rework, since it conflicts with the generic `Command`

**Comment by phish108** [comment]
thank you @Rody-Oldenhuis. Version `v1.1.64` fixes this issue.
