### ISSUE TITLE
`node12` is deprecated in favor of `node16`

### ISSUE THREAD

**Issue by Rody-Oldenhuis** [phish108/autotag-action#191]
As per [this 2022 blog post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), `node12` is going to be deprecated. 

This currently gives a warning: 

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: phish108/autotag-action@1.1.53.

According to the post above, this will start breaking things sometime this summer.

Looks like it should be as simple as updating `action.yml`

**Comment by phish108** [comment]
@Rody-Oldenhuis Thank you for this remark. 

I bumped the node version up to node18. Version 1.1.54 should work again without complaints.

**Comment by phish108** [comment]
v1.1.56 works, closing the issue
